#!/bin/bash

cd $(dirname $0)

mkdir -p $HOMEDIR/autossh/
cp -f ./autossh $HOMEDIR/autossh/

CONFIG_FILE=`cd $HOMEDIR/autossh/ && pwd`/config.json
if [[ ! -f ${CONFIG_FILE} ]]; then
    cp ./config.json $HOMEDIR/autossh/
fi

HAS_ALIAS=`cat $HOMEDIR/.bash_profile | grep autossh | wc -l`
if [[ ${HAS_ALIAS} -eq 0 ]]; then
    echo "export PATH=$PATH:~/autossh/" >> ~/.bash_profile
fi

source ~/.bash_profile

~/autossh/autossh
